[tool.poetry]
name = "customeranalytics"
version = "0.1"
description = "Funnels, Cohorts, A/B Tests, e-commerce, CLV Prediction, Product Analytics, Churn, Anomaly Detection, Customer Segmentation, RFM, Statistics"
authors = ["Caglan Akpinar <cakpinar23@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/caglanakpinar/customer_analytics"
repository = "https://github.com/caglanakpinar/customer_analytics"
keywords = [
    "Funnels", "Cohorts", "A/B Tests", "e-commerce", "CLV Prediction",
    "Product Analytics", "Churn", "Anomaly Detection",
    "Customer Segmentation", "RFM", "Statistics", "Customer Analytics"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
packages = [
    { include = "customeranalytics" }
]
include = ["customeranalytics/web/**", "customeranalytics/docs/**"]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
PyYAML = "*"
psycopg2-binary = "*"
psutil = "*"
requests = "*"
urllib3 = "*"
email_validator = "*"
flask_login = "*"
flask = "*"
python-decouple = "*"
flask_migrate = "*"
flask_wtf = "*"
sqlalchemy = "*"
screeninfo = "*"
numpy = "*"
pandas = "*"
schedule = "*"
h2o = "*"
keras-tuner = "*"
tensorflow = ">=2.18.0,<2.20.0"
clv-prediction = "*"
abtest = "*"
pygeohash = "*"
random2 = "*"
pytest-shutil = "*"
python-math = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"